### ISSUE TITLE
bug: pseudo class selectors fails to parse class_names on attribute selectors

### ISSUE THREAD

**Issue by mohamedmansour** [tree-sitter/tree-sitter-css#57]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-css

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.24.3 (bdfe32402e85673bbc693216f0a6ef72c98bb665)

### Describe the bug

All attribute selectors in CSS are allowed to have class name selectors attached to it. For example, adding a `:hover`. But the parser fails with ERROR nodes.

It seems any selector after the attribute selector `[a="b"]` if it is within a pseudo_class_selector `:host(....)` fails. That should be pass.

This is needed to support HTML Web Components, where `:host` and `:host-context` are used to decorate the components. These two are missing from `tree-sitter-css` which accept selectors as parameters.

### Steps To Reproduce/Bad Parse Tree

```
(stylesheet [0, 0] - [1, 1]
  (rule_set [0, 0] - [1, 1]
    (selectors [0, 0] - [0, 20]
      (pseudo_class_selector [0, 0] - [0, 20]
        (class_name [0, 1] - [0, 5])
        (arguments [0, 5] - [0, 20]
          (grid_value [0, 6] - [0, 13]
            (plain_value [0, 7] - [0, 12]))
          (ERROR [0, 13] - [0, 14])
          (plain_value [0, 14] - [0, 19]))))
    (block [0, 21] - [1, 1])))
```

### Expected Behavior/Parse Tree

I expect a `class_name` to be attached after the attribute selector `[a="b"]`.
```
(stylesheet [0, 0] - [5, 1]
  (rule_set [0, 0] - [2, 1]
    (selectors [0, 0] - [0, 14]
      (pseudo_class_selector [0, 0] - [0, 14]
        (class_name [0, 1] - [0, 5])
        (arguments [0, 5] - [0, 14]
          (grid_value [0, 6] - [0, 13]
            (plain_value [0, 7] - [0, 12])))))
          (class_name [3, 8] - [3, 13])))
```

### Repro

```CSS
:host([a="b"]:hover) {
}
```

**Comment by mohamedmansour** [comment]
When looking at the grammar for `pseudo_class_selector` it seems the pseudo classes are defined manually, `:has`, `:not`, `:is`, `:where`. When I added `:host` to that `CHOICE` it worked.

But there are many pseudo class selectors, I am not familiar with tree-sitter, but should we support any string?

https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes

A

[:active](https://developer.mozilla.org/en-US/docs/Web/CSS/:active)
[:any-link](https://developer.mozilla.org/en-US/docs/Web/CSS/:any-link)
[:autofill](https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill)
B

[:blank](https://developer.mozilla.org/en-US/docs/Web/CSS/:blank) Experimental
C

[:checked](https://developer.mozilla.org/en-US/docs/Web/CSS/:checked)
[:current](https://developer.mozilla.org/en-US/docs/Web/CSS/:current)
D

[:default](https://developer.mozilla.org/en-US/docs/Web/CSS/:default)
[:defined](https://developer.mozilla.org/en-US/docs/Web/CSS/:defined)
[:dir()](https://developer.mozilla.org/en-US/docs/Web/CSS/:dir)
[:disabled](https://developer.mozilla.org/en-US/docs/Web/CSS/:disabled)
E

[:empty](https://developer.mozilla.org/en-US/docs/Web/CSS/:empty)
[:enabled](https://developer.mozilla.org/en-US/docs/Web/CSS/:enabled)
F

[:first](https://developer.mozilla.org/en-US/docs/Web/CSS/:first)
[:first-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:first-child)
[:first-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:first-of-type)
[:focus](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus)
[:focus-visible](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible)
[:focus-within](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within)
[:fullscreen](https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen)
[:future](https://developer.mozilla.org/en-US/docs/Web/CSS/:future) Experimental
H

[:has()](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) Experimental
[:host](https://developer.mozilla.org/en-US/docs/Web/CSS/:host)
[:host()](https://developer.mozilla.org/en-US/docs/Web/CSS/:host)
[:host-context()](https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context) Experimental
[:hover](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover)
I

[:indeterminate](https://developer.mozilla.org/en-US/docs/Web/CSS/:indeterminate)
[:in-range](https://developer.mozilla.org/en-US/docs/Web/CSS/:in-range)
[:invalid](https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid)
[:is()](https://developer.mozilla.org/en-US/docs/Web/CSS/:is)
L

[:lang()](https://developer.mozilla.org/en-US/docs/Web/CSS/:lang)
[:last-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:last-child)
[:last-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:last-of-type)
[:left](https://developer.mozilla.org/en-US/docs/Web/CSS/:left)
[:link](https://developer.mozilla.org/en-US/docs/Web/CSS/:link)
[:local-link](https://developer.mozilla.org/en-US/docs/Web/CSS/:local-link)
M

[:modal](https://developer.mozilla.org/en-US/docs/Web/CSS/:modal)
N

[:not()](https://developer.mozilla.org/en-US/docs/Web/CSS/:not)
[:nth-child()](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child)
[:nth-last-child()](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-child)
[:nth-last-of-type()](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-of-type)
[:nth-of-type()](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type)
O

[:only-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:only-child)
[:only-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:only-of-type)
[:optional](https://developer.mozilla.org/en-US/docs/Web/CSS/:optional)
[:out-of-range](https://developer.mozilla.org/en-US/docs/Web/CSS/:out-of-range)
P

[:past](https://developer.mozilla.org/en-US/docs/Web/CSS/:past)
[:paused](https://developer.mozilla.org/en-US/docs/Web/CSS/:paused)
[:picture-in-picture](https://developer.mozilla.org/en-US/docs/Web/CSS/:picture-in-picture)
[:placeholder-shown](https://developer.mozilla.org/en-US/docs/Web/CSS/:placeholder-shown)
[:playing](https://developer.mozilla.org/en-US/docs/Web/CSS/:playing)
[:popover-open](https://developer.mozilla.org/en-US/docs/Web/CSS/:popover-open)
R

[:read-only](https://developer.mozilla.org/en-US/docs/Web/CSS/:read-only)
[:read-write](https://developer.mozilla.org/en-US/docs/Web/CSS/:read-write)
[:required](https://developer.mozilla.org/en-US/docs/Web/CSS/:required)
[:right](https://developer.mozilla.org/en-US/docs/Web/CSS/:right)
[:root](https://developer.mozilla.org/en-US/docs/Web/CSS/:root)
S

[:scope](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope)
[:state()](https://developer.mozilla.org/en-US/docs/Web/CSS/:state)
T

[:target](https://developer.mozilla.org/en-US/docs/Web/CSS/:target)
[:target-within](https://developer.mozilla.org/en-US/docs/Web/CSS/:target-within) Experimental
U

[:user-invalid](https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid)
V

[:valid](https://developer.mozilla.org/en-US/docs/Web/CSS/:valid)
[:visited](https://developer.mozilla.org/en-US/docs/Web/CSS/:visited)
W

[:where()](https://developer.mozilla.org/en-US/docs/Web/CSS/:where)

**Comment by mohamedmansour** [comment]
@amaanq what is the recommendation for supporting all those pseudo class selectors?

**Comment by savetheclocktower** [comment]
> Hey @savetheclocktower do you think this is related to your last change?

Almost certainly, but it also tells us what the fix should be.

The problem was that, inside of a pseudoclass that takes parameters, the parser incorrectly preferred to parse some selectors as `plain_value`s . [The full explanation is here.](https://github.com/tree-sitter/tree-sitter-css/issues/45#issuecomment-1911282692)

My fix was to split pseudoclasses with parameters into two buckets — those that expect a selector and those that don't. That fixes the problem, but creates a different problem of maintenance: whenever new pseudoclasses are added that take a selector as a parameter, they have to be added to the list.

I suppose I missed this one when I submitted the fix — I thought the four I named were the only ones that took a selector. You're right that the quickest fix is to add `:host` to the list.

---

This cries out for a more thorough fix, but I'm not sure what form it would take. Pseudoclasses vary wildly in what sorts of parameters they allow. Here's what you'd want to do:

* Reduce the list in your earlier comment to only the ones that accept parameters
* Describe valid input for each pseudoclass
* See if you can come up with an unambiguous rule that can parse all acceptable input for all different types of pseudoclasses

The last item sounds hard, but it might not be! The problem is that the `pseudo_class_arguments` rule accepts a number of things including `plain_value` — which is rather broad and will always be preferred even when we should lex something as a selector. It's possible that `pseudo_class_arguments` can be rewritten in a way that doesn't use `plain_value` and instead uses something more restrictive (and is maybe aliased to `plain_value`).

But pseudoclass parameters are an anything-goes nightmare! I just recently realized that `:nth-child` and `:nth-last-child` pseudoclasses can be “qualified” with a selector as follows:

```css
div > :nth-child(1 of p.active) {
  // The first child of a `div` among those that match the selector `p.active`
}
```

This has the same problem that my change was trying to solve: `of` is parsed as a `plain_value` (which is fine), but `p.active` is as well.

So I think the right answer is still to be more restrictive than we currently are in how we parse all pseudoclass arguments, whether or not we maintain a special “selector-only” list. The `_value` rule has lots of the things we'd want to identify in that context, but is too broad.

**Comment by savetheclocktower** [comment]
Anyway, if you wanted to submit a quick fix, you'd just need to add `host` and `host-context` to the list of pseudoclasses that take only selectors as parameters.

**Comment by savetheclocktower** [comment]
> But there are many pseudo class selectors, I am not familiar with tree-sitter, but should we support any string?

To be clear: all others are supported as well, even those that aren't specifically mentioned. You could write `p:foo(bar)` and it would be parsed correctly, even though that's not a valid pseudoclass right now.

The ones that are mentioned by name are those that need special handling for the reasons mentioned above.

**Comment by mohamedmansour** [comment]
Great work @savetheclocktower!  I just verified all the pseudo selectors are now handled after your PR. Really appreciate the level of detail with your posts!  Hopefully that gets merged soon!

**Comment by mohamedmansour** [comment]
@amaanq  I was verifying it with:

```
    "tree-sitter": "^0.22.1",
    "tree-sitter-css": "^0.23.1",
``` 

And it is producing  more errors than before:
```
(stylesheet [0, 0] - [0, 23])
  (ERROR [0, 0] - [0, 6])
    (class_name [0, 1] - [0, 5])
  (rule_set [0, 6] - [0, 23])
    (selectors [0, 6] - [0, 19])
      (pseudo_class_selector [0, 6] - [0, 19])
        (attribute_selector [0, 6] - [0, 13])
          (attribute_name [0, 7] - [0, 8])
          (string_value [0, 9] - [0, 12])
            (string_content [0, 10] - [0, 11])
        (class_name [0, 14] - [0, 19])
          (identifier [0, 14] - [0, 19])
    (ERROR [0, 19] - [0, 20])
    (block [0, 21] - [0, 23])
```

for this example:
